# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f29bec24bc4dc7362b7bb20e6eea585623804e613a710d3c414b22f1e9f29a99946fc87640c0cfeec7cdd091ee8079768ecc7d8c270be6f608aa68f0ed0de47

test:
  secret_key_base: f24e98a984808a55513bfd816e97c01e434a4f7cd06082ca818d2db76f20984b063a0cf5b6bf80a8811551c9a8c1ab5e2e727bd185ea29f5b31f61e97dc463e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
